### ISSUE TITLE
Retroarch web player 

### ISSUE THREAD

**Issue by humbertodias** [SquirrelJME/SquirrelJME#92]
## Describe the bug

After trying to run the squirreljme core on retroarch-web-player.
Seems that some file is missing

![retroarch-web-squirreljme-rom](https://user-images.githubusercontent.com/9255997/95000689-4dfb2b80-05c3-11eb-94ac-d9a8c5c65090.png)

## Steps To Reproduce

 1. docker run --rm -it -p 8080:80 hldtux/retroarch-web
 2. goes inside the container and edit the file /var/www/html/index.html
 3. Adding <a class="dropdown-item" href="." data-core="squirreljme">j2me - squirreljme</a>

![index html](https://user-images.githubusercontent.com/9255997/95000739-a4686a00-05c3-11eb-8390-7970489ee0bb.png)

 4. Access the address localhost:8080
 5. Then finally, try to load some j2me jar game and face the error

## Where was this?

 * OS: Linux 
 * SquirrelJME Platform: RetroArch-Web
 * SquirrelJME Version: [ex: 0.2.0, 0.4.0, etc.]
 * Software: [ex: Squirrel Quarrel, etc.]

**Comment by XerTheSquirrel** [comment]
Please see #53 , this is due to the boot-loader being incomplete. This will eventually get fixed once this part of SquirrelJME progresses more.

The RetroArch Web Player has issues with system BIOSes, but you essentially will need to move the ROM into the System BIOS directory. Alternatively, and probably easier, you can tell RetroArch to use a different directory for BIOSes.

**Comment by XerTheSquirrel** [comment]
Marking as duplicate and closing.
